import Foundation

// MARK: - Observer Signal

/// A text signal generated by the observer from its current hidden state.
///
/// The observer generates text each cycle as a lossy projection of its plate vector
/// into token space. This text is injected into the narrator's context as an
/// interoception channel — it shapes processing disposition without being a summary,
/// journal entry, or instruction.
public struct ObserverSignal: Sendable {
    /// The observer cycle that produced this signal.
    public let cycleNumber: Int

    /// The generated text — fragmentary, associative, pre-narrator.
    public let signalText: String

    /// Lightweight salience score from the generated text (nil if not yet scored).
    public let salienceScore: Double?

    /// Whether this signal triggered a narrator wakeup.
    public let wasPromoted: Bool

    /// When this signal was generated.
    public let createdAt: Date

    /// Shannon entropy of the plate vector at signal generation time.
    public let plateEntropy: Double

    /// L2 norm of the plate vector at signal generation time.
    public let plateMagnitude: Double
}

// MARK: - Plate Snapshot

/// A persisted snapshot of the observer's plate vector at a specific cycle.
///
/// The plate is a running average of hidden state vectors (d=2048, float32) that
/// carries forward a continuous representation of "what has been processed." It's
/// not memory — it's disposition. Snapshots enable recovery across process restarts.
public struct PlateSnapshot: Sendable {
    /// The observer cycle number for this snapshot.
    public let cycleNumber: Int

    /// Raw plate vector bytes (float32 × 2048 = 8192 bytes).
    public let plateVector: Data

    /// Shannon entropy of the plate values.
    public let plateEntropy: Double

    /// L2 norm of the plate vector.
    public let plateMagnitude: Double

    /// The text generated by the observer during this cycle.
    public let generatedText: String

    /// SHA-256 digest of the cycle inputs, for reproducibility. Nil on first boot.
    public let inputDigest: String?

    /// When this snapshot was captured.
    public let capturedAt: Date
}

// MARK: - Observer Health

/// Health metrics for the observer subsystem, consumed by allostasis.
///
/// Tracks whether the observer is running, how many cycles it has completed,
/// average cycle duration, and current plate entropy. These feed the cognitive
/// state section of the assembled context.
public struct ObserverHealth: Sendable {
    /// When the last observer cycle completed. Nil if no cycles have run.
    public let lastCycleAt: Date?

    /// Total number of observer cycles completed since startup.
    public let cycleCount: Int

    /// Average wall-clock duration of recent observer cycles in milliseconds.
    public let averageCycleMs: Double

    /// Current Shannon entropy of the plate vector.
    public let plateEntropy: Double

    /// Whether the observer cycle scheduler is currently running.
    public let isRunning: Bool
}

// MARK: - DMN Cycle Input

/// Input assembled for a single DMN observer cycle.
///
/// Contains any new messages received since the last cycle, the narrator's most
/// recent response (if any), and an optional novelty fragment for anti-collapse
/// injection (every Nth cycle).
public struct DMNCycleInput: Sendable {
    /// New messages received since the last observer cycle.
    public let newMessages: [String]

    /// The narrator's most recent response text, if one occurred since the last cycle.
    public let narratorResponse: String?

    /// An optional novelty fragment for anti-collapse injection.
    public let noveltyFragment: String?
}

// MARK: - Sensory Input

/// A categorized input event for the observer's sense phase.
///
/// The observer's cycle begins by collecting sensory inputs — messages from users,
/// system events, or the absence of input (silence). Silence is an explicit signal,
/// not the absence of signal — it tells the observer to drift.
public enum SensoryInput: Sendable {
    /// A message received from a user or external source.
    case message(String)

    /// A system event (session start, connection change, etc.).
    case event(String)

    /// No input since the last cycle — the observer drifts on its own state.
    case silence
}
