import Foundation
import GRDB

/// GRDB record for a persisted plate vector snapshot.
///
/// Maps to the `plate_snapshots` table. Uses autoincremented primary key
/// (`snapshotId`) so conforms to `MutablePersistableRecord` with `didInsert`.
public struct PlateSnapshotRecord: Codable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "plate_snapshots"

    /// Database-assigned autoincrement ID. `nil` before first insert.
    public var snapshotId: Int64?

    /// The observer cycle number for this snapshot.
    public var cycleNumber: Int

    /// Raw plate vector bytes (float32 × 2048 = 8192 bytes).
    public var plateVector: Data

    /// Shannon entropy of the plate values.
    public var plateEntropy: Double

    /// L2 norm of the plate vector.
    public var plateMagnitude: Double

    /// The text generated by the observer during this cycle.
    public var generatedText: String

    /// SHA-256 digest of the cycle inputs, for reproducibility.
    public var inputDigest: String?

    /// ISO 8601 timestamp of when this snapshot was captured.
    public var capturedAt: String

    public mutating func didInsert(_ inserted: InsertionSuccess) {
        snapshotId = inserted.rowID
    }
}

/// GRDB record for archived (downsampled) plate vectors over a cycle range.
///
/// Maps to the `plate_archive` table. Stores mean vectors averaged over a range
/// of cycles, with entropy bounds for the range.
public struct PlateArchiveRecord: Codable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "plate_archive"

    /// Database-assigned autoincrement ID. `nil` before first insert.
    public var archiveId: Int64?

    /// String representation of the archived cycle range (e.g., "100-200").
    public var cycleRange: String

    /// Mean vector averaged over the cycle range.
    public var meanVector: Data

    /// Maximum entropy observed in the range.
    public var maxEntropy: Double

    /// Minimum entropy observed in the range.
    public var minEntropy: Double

    /// ISO 8601 timestamp of when this archive was created.
    public var archivedAt: String

    public mutating func didInsert(_ inserted: InsertionSuccess) {
        archiveId = inserted.rowID
    }
}

/// GRDB record for an observer signal generated during a DMN cycle.
///
/// Maps to the `observer_signals` table. Each signal is the text generated by the
/// observer from its current hidden state — the interoception channel to the narrator.
public struct ObserverSignalRecord: Codable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "observer_signals"

    /// Database-assigned autoincrement ID. `nil` before first insert.
    public var signalId: Int64?

    /// The observer cycle that produced this signal.
    public var cycleNumber: Int

    /// The generated text — fragmentary, associative, pre-narrator.
    public var signalText: String

    /// Lightweight salience score from the generated text.
    public var salienceScore: Double?

    /// Whether this signal triggered a narrator wakeup (0 = no, 1 = yes).
    public var wasPromoted: Int

    /// ISO 8601 timestamp of when this signal was generated.
    public var createdAt: String

    public mutating func didInsert(_ inserted: InsertionSuccess) {
        signalId = inserted.rowID
    }
}
